// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Launcher wrapper for Slang-compiled backward kernels

#include "backward_kernel.h"
#include <cuda_runtime.h>

// Forward declarations for Slang-generated CUDA kernels
// The actual kernels are generated by slangc in backwards_kernel_cuda.cu

// Slang generates kernels with this signature pattern for [CudaKernel] functions
extern "C" __global__ void backwards_kernel(
    float* last_state,
    int* iters,
    int* tri_collection,
    float* ray_origins,
    float* ray_directions,
    float* means,
    float* scales,
    float* quats,
    float* densities,
    float* features,
    float* dL_dmeans,
    float* dL_dscales,
    float* dL_dquats,
    float* dL_ddensities,
    float* dL_dfeatures,
    float* dL_drayos,
    float* dL_drayds,
    float* dL_dmeans2D,
    float* dL_dinitial_drgb,
    int* touch_count,
    float* dL_doutputs,
    float* wcts,
    float tmin,
    float tmax,
    float max_prim_size,
    unsigned int max_iters,
    unsigned int num_rays,
    unsigned int num_prims,
    unsigned int feature_size,
    unsigned int num_wcts
);

extern "C" __global__ void backwards_initial_drgb_kernel(
    float* ray_origins,
    float* ray_directions,
    float* means,
    float* scales,
    float* quats,
    float* densities,
    float* features,
    float* dL_ddensities,
    float* dL_dfeatures,
    int* initial_inds,
    float* dL_dinitial_drgb,
    int* touch_count,
    float tmin,
    unsigned int num_rays,
    unsigned int num_initial_inds,
    unsigned int feature_size
);

void launch_backwards_kernel(
    float* last_state,
    int* iters,
    int* tri_collection,
    float* ray_origins,
    float* ray_directions,
    float* means,
    float* scales,
    float* quats,
    float* densities,
    float* features,
    float* dL_dmeans,
    float* dL_dscales,
    float* dL_dquats,
    float* dL_ddensities,
    float* dL_dfeatures,
    float* dL_drayos,
    float* dL_drayds,
    float* dL_dmeans2D,
    float* dL_dinitial_drgb,
    int* touch_count,
    float* dL_doutputs,
    float* wcts,
    float tmin,
    float tmax,
    float max_prim_size,
    uint32_t max_iters,
    uint32_t num_rays,
    uint32_t num_prims,
    uint32_t feature_size,
    uint32_t num_wcts,
    cudaStream_t stream
) {
    const int block_size = 256;
    const int grid_size = (num_rays + block_size - 1) / block_size;

    backwards_kernel<<<grid_size, block_size, 0, stream>>>(
        last_state, iters, tri_collection,
        ray_origins, ray_directions,
        means, scales, quats, densities, features,
        dL_dmeans, dL_dscales, dL_dquats, dL_ddensities, dL_dfeatures,
        dL_drayos, dL_drayds, dL_dmeans2D,
        dL_dinitial_drgb, touch_count,
        dL_doutputs, wcts,
        tmin, tmax, max_prim_size, max_iters, num_rays, num_prims, feature_size, num_wcts
    );
}

void launch_backwards_initial_drgb_kernel(
    float* ray_origins,
    float* ray_directions,
    float* means,
    float* scales,
    float* quats,
    float* densities,
    float* features,
    float* dL_ddensities,
    float* dL_dfeatures,
    int* initial_inds,
    float* dL_dinitial_drgb,
    int* touch_count,
    float tmin,
    uint32_t num_rays,
    uint32_t num_initial_inds,
    uint32_t feature_size,
    cudaStream_t stream
) {
    dim3 block_size(64, 16);
    dim3 grid_size((num_rays + block_size.x - 1) / block_size.x,
                   (num_initial_inds + block_size.y - 1) / block_size.y);

    backwards_initial_drgb_kernel<<<grid_size, block_size, 0, stream>>>(
        ray_origins, ray_directions,
        means, scales, quats, densities, features,
        dL_ddensities, dL_dfeatures,
        initial_inds, dL_dinitial_drgb, touch_count,
        tmin, num_rays, num_initial_inds, feature_size
    );
}
