// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <cuda.h>
#include <cuda_runtime.h>
#include <optix.h>

#include <cstdint>

#include "structs.h"

using uint = uint32_t;

// ============================================================================
// Embedded OptiX-IR Data (generated by bin2c)
// ============================================================================

extern "C" {
extern const unsigned char shaders_optixir[];
extern const size_t shaders_optixir_size;
extern const unsigned char fast_shaders_optixir[];
extern const size_t fast_shaders_optixir_size;
}

// ============================================================================
// SBT Record Types
// ============================================================================

template <typename T>
struct __align__(OPTIX_SBT_RECORD_ALIGNMENT) SbtRecord {
    char header[OPTIX_SBT_RECORD_HEADER_SIZE];
    T data;
};

struct __align__(OPTIX_SBT_RECORD_ALIGNMENT) EmptySbtRecord {
    char header[OPTIX_SBT_RECORD_HEADER_SIZE];
};

struct RayGenData {};
struct MissData { float3 backgroundColor; };
struct HitGroupData {};

using RayGenSbtRecord   = SbtRecord<RayGenData>;
using MissSbtRecord     = SbtRecord<MissData>;
using HitGroupSbtRecord = SbtRecord<HitGroupData>;

// ============================================================================
// Slang-Compatible Buffer Type
// ============================================================================

template <typename T>
struct __align__(16) StructuredBuffer {
    T*     data;
    size_t size;
};

// ============================================================================
// Launch Parameters - matches Slang shader global variables
// ============================================================================

struct __align__(128) Params {
    // Output Buffers
    StructuredBuffer<float4>      image;
    StructuredBuffer<uint>        iters;
    StructuredBuffer<uint>        last_face;
    StructuredBuffer<uint>        touch_count;
    StructuredBuffer<float4>      last_dirac;
    StructuredBuffer<SplineState> last_state;
    StructuredBuffer<int>         tri_collection;

    // Input Ray Buffers
    StructuredBuffer<float3>      ray_origins;
    StructuredBuffer<float3>      ray_directions;

    // Camera
    Cam camera;

    // Model Attribute Buffer (legacy)
    StructuredBuffer<__half>      half_attribs;

    // Model Data Buffers
    StructuredBuffer<float3>      means;
    StructuredBuffer<float3>      scales;
    StructuredBuffer<float4>      quats;
    StructuredBuffer<float>       densities;
    StructuredBuffer<float>       features;

    // Render Parameters
    uint   sh_degree;
    uint   max_iters;
    float  tmin;
    float  tmax;

    // Initial DRGB Buffer
    StructuredBuffer<float4>      initial_drgb;

    // Additional Parameters
    float  max_prim_size;
    float  _padding[3];

    // Acceleration Structure Handle
    OptixTraversableHandle handle;
};

// ============================================================================
// Forward Pass Class
// ============================================================================

class Forward {
public:
    Forward() = default;

    Forward(
        const OptixDeviceContext& context,
        int8_t device,
        const Primitives& model,
        const bool enable_backward
    );

    ~Forward() noexcept(false);

    // Non-copyable
    Forward(const Forward&) = delete;
    Forward& operator=(const Forward&) = delete;

    // Movable
    Forward(Forward&& other) noexcept;
    Forward& operator=(Forward&& other) noexcept;

    // Main interface
    void trace_rays(
        const OptixTraversableHandle& handle,
        size_t numRays,
        float3* rayOrigins,
        float3* rayDirections,
        void* imageOut,
        uint shDegree,
        float tmin,
        float tmax,
        float4* initialDrgb,
        Cam* camera = nullptr,
        size_t maxIters = 10000,
        float maxPrimSize = 3.0f,
        uint* iters = nullptr,
        uint* lastFace = nullptr,
        uint* touchCount = nullptr,
        float4* lastDirac = nullptr,
        SplineState* lastState = nullptr,
        int* triCollection = nullptr,
        int* dTouchCount = nullptr,
        int* dTouchInds = nullptr
    );

    void reset_features(const Primitives& model);

    // Public members
    bool   enable_backward = false;
    size_t num_prims       = 0;

private:
    void cleanup();

    // OptiX context
    OptixDeviceContext m_context = nullptr;
    int8_t             m_device  = -1;

    // Model reference
    const Primitives*  m_model = nullptr;

    // Pipeline objects
    OptixModule        m_module      = nullptr;
    OptixPipeline      m_pipeline    = nullptr;
    OptixProgramGroup  m_raygenGroup = nullptr;
    OptixProgramGroup  m_missGroup   = nullptr;
    OptixProgramGroup  m_hitGroup    = nullptr;

    // Shader Binding Table
    OptixShaderBindingTable m_sbt = {};

    // Device memory
    CUdeviceptr m_dParams = 0;

    // Host-side launch parameters
    Params m_params = {};

    // Pipeline compile options
    OptixPipelineCompileOptions m_pipelineOptions = {};
};
