// Launcher for Slang-generated backward kernel
// This file bridges the C++ interface with the Slang-generated CUDA code

#include <cuda_runtime.h>
#include <cstdint>

// Forward declaration of the Slang-generated CUDA kernel
// The kernel is generated by slangc from backward.slang with [CudaDeviceExport]
// Parameter order matches the global declarations in backward.slang
extern "C" __global__ void gaussianrt_backward(
    // Input StructuredBuffers
    const float* g_final_states,
    const int* g_sample_counts,
    const int* g_sample_indices,
    const float* g_positions,
    const float* g_scales,
    const float* g_rotations,
    const float* g_opacities,
    const float* g_features,
    const float* g_ray_origins,
    const float* g_ray_directions,
    const float* g_grad_colors,
    const float* g_grad_depths,
    // Output RWStructuredBuffers
    float* g_grad_positions,
    float* g_grad_scales,
    float* g_grad_rotations,
    float* g_grad_opacities,
    float* g_grad_features,
    float* g_grad_ray_origins,
    float* g_grad_ray_directions,
    // Uniform parameters
    uint32_t g_num_rays,
    uint32_t g_max_samples,
    uint32_t g_feature_dim,
    float g_t_min
);

namespace gaussian_rt {

// ============================================================================
// Launcher Function
// This provides the same interface expected by volume_renderer.cpp
// but calls the Slang-generated autodiff kernel
// ============================================================================

extern "C" void launch_backward_kernel(
    // Forward outputs
    const float* final_states,
    const float* last_points,
    const int* sample_counts,
    const int* sample_indices,
    // Scene data
    const float* positions,
    const float* scales,
    const float* rotations,
    const float* opacities,
    const float* features,
    uint32_t num_elements,
    uint32_t feature_dim,
    // Ray data
    const float* ray_origins,
    const float* ray_dirs,
    uint32_t num_rays,
    // Upstream gradients
    const float* grad_colors,
    const float* grad_depths,
    const float* grad_distortions,
    // Parameters
    float t_min,
    float t_max,
    uint32_t max_samples,
    uint32_t sh_degree,
    // Output gradients
    float* grad_positions,
    float* grad_scales,
    float* grad_rotations,
    float* grad_opacities,
    float* grad_features,
    float* grad_ray_origins,
    float* grad_ray_dirs,
    cudaStream_t stream
) {
    // Set up kernel launch parameters
    constexpr uint32_t BLOCK_SIZE = 256;
    uint32_t num_blocks = (num_rays + BLOCK_SIZE - 1) / BLOCK_SIZE;

    dim3 grid_dim(num_blocks, 1, 1);
    dim3 block_dim(BLOCK_SIZE, 1, 1);

    // Call the Slang-generated backward kernel
    // The kernel signature is generated by slangc from backward.slang
    // Parameters map to the StructuredBuffer/RWStructuredBuffer/uniform declarations
    gaussianrt_backward<<<grid_dim, block_dim, 0, stream>>>(
        // Input buffers (StructuredBuffer)
        final_states,           // g_final_states
        sample_counts,          // g_sample_counts
        sample_indices,         // g_sample_indices
        positions,              // g_positions
        scales,                 // g_scales
        rotations,              // g_rotations
        opacities,              // g_opacities
        features,               // g_features
        ray_origins,            // g_ray_origins
        ray_dirs,               // g_ray_directions
        grad_colors,            // g_grad_colors
        grad_depths,            // g_grad_depths
        // Output buffers (RWStructuredBuffer)
        grad_positions,         // g_grad_positions
        grad_scales,            // g_grad_scales
        grad_rotations,         // g_grad_rotations
        grad_opacities,         // g_grad_opacities
        grad_features,          // g_grad_features
        grad_ray_origins,       // g_grad_ray_origins
        grad_ray_dirs,          // g_grad_ray_directions
        // Uniform parameters
        num_rays,               // g_num_rays
        max_samples,            // g_max_samples
        feature_dim,            // g_feature_dim
        t_min                   // g_t_min
    );

    // Check for launch errors
    cudaError_t err = cudaGetLastError();
    if (err != cudaSuccess) {
        // Log error but don't throw - let the caller handle synchronization
    }
}


} // namespace gaussian_rt
