# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generate OptiX intrinsics for Slang targeting CUDA/OptiX 9.1.

This script generates optix-intrinsics.slang with:
1. Payload getter/setter functions for 32 registers
2. Attribute getter functions for up to 8 attributes
3. optixReportHit variants for custom intersection shaders
4. optixTrace32 with 32 individual inout payload parameters
"""

util = """// Generated by gen_optix_util.py
// OptiX 9.1 compatible intrinsics for Slang -> CUDA compilation

uint optixGetHitKind() {
  __intrinsic_asm "optixGetHitKind()";
}

"""

# Generate individual payload getter/setter functions
for n in range(32):
    util += f"""
void set_payload{n}(uint v) {{
  __intrinsic_asm "optixSetPayload_{n}($0)";
}}

uint get_payload{n}() {{
  __intrinsic_asm "optixGetPayload_{n}()";
}}
"""

# Generate attribute getters
for n in range(8):
    util += f"""
uint optixGetAttribute_{n}() {{
  __intrinsic_asm "optixGetAttribute_{n}()";
}}
"""

# Generate optixReportHit variants
for n in range(8):
    hit_args = ', '.join([f"${i+2}" for i in range(n+1)])
    fn_args = ", ".join([f"in uint p{i}" for i in range(n+1)])
    util += f"""
bool optixReportHit(float t, uint hitKind, {fn_args}) {{
  __intrinsic_asm "optixReportIntersection($0, $1, {hit_args})";
}}
"""

# Unified set_payload function with switch
util += """
[ForceInline]
void set_payload(uint i, uint val) {
    switch (i) {
"""

for n in range(32):
    util += f"""    case {n}:
        return set_payload{n}(val);
"""

util += """    }
}
"""

# Unified get_payload function with switch
util += """
[ForceInline]
uint get_payload(uint i) {
    switch (i) {
"""

for n in range(32):
    util += f"""    case {n}:
        return get_payload{n}();
"""

util += """    }
}
"""

# Generate optixTrace32 with 32 individual inout parameters
# This avoids the complex array operations in __intrinsic_asm
trace_params = ", ".join([f"inout uint p{i}" for i in range(32)])
trace_args = ", ".join([f"p{i}" for i in range(32)])

util += f"""
// optixTrace with 32 individual payload parameters
// Use this in raygen shader to avoid module compilation issues
void optixTrace32(
    in RaytracingAccelerationStructure handle,
    in float3 ray_origin,
    in float3 ray_direction,
    in float tmin,
    in float tmax,
    {trace_params}
) {{
  __intrinsic_asm R"(
    optixTrace(
            $0,
            $1,
            $2,
            $3,
            $4,
            0.0f,                // rayTime
            OptixVisibilityMask( 255 ),
            OPTIX_RAY_FLAG_NONE,
            0,                   // SBT offset
            0,                   // SBT stride
            0,                   // missSBTIndex
            $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36);
  )";
}}

// Helper to trace with payload array - wraps optixTrace32
// Call this from raygen shader
[ForceInline]
void traceRayWithPayload(
    in RaytracingAccelerationStructure handle,
    in float3 ray_origin,
    in float3 ray_direction,
    in float tmin,
    in float tmax,
    inout uint payload[32]
) {{
    optixTrace32(
        handle,
        ray_origin,
        ray_direction,
        tmin,
        tmax,
        payload[0], payload[1], payload[2], payload[3],
        payload[4], payload[5], payload[6], payload[7],
        payload[8], payload[9], payload[10], payload[11],
        payload[12], payload[13], payload[14], payload[15],
        payload[16], payload[17], payload[18], payload[19],
        payload[20], payload[21], payload[22], payload[23],
        payload[24], payload[25], payload[26], payload[27],
        payload[28], payload[29], payload[30], payload[31]
    );
}}
"""

with open("optix-intrinsics.slang", "w") as f:
    f.write(util)

print("Generated optix-intrinsics.slang successfully.")
